import {test} from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import fs from 'node:fs';import vm from 'node:vm';
const cache={};function mod(name){if(cache[name])return cache[name];let source=fs.readFileSync(`app/lib/${name}.ts`,'utf8');const exports={};const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,require:id=>id==='./operationalDate'?{operationalDateForReport:r=>r.operationalDate||r.date}:mod(id.slice(2)),process:{env:{}},Intl,Date});return cache[name]=exports;}
const {generateWhatsAppMessage,buildWhatsAppUrl}=mod('whatsapp');
test('Saved operational night date, Malaysian final save time and real totals',()=>{const r={date:'2026-10-04',operationalDate:'2026-10-03',shift:'Malam',stats:{l1:1,l2:2,l3:3,l4:4,l5:5,asthmaBay:6},calls:{mecc:2,operator:1,awam:0,palsu:0}};const msg=generateWhatsAppMessage(r,'2026-10-03T18:30:00Z');assert.match(msg,/3 Oktober 2026/);assert.match(msg,/Shift: Malam/);assert.match(msg,/02:30/);assert.match(msg,/Jumlah Pesakit: 21/);assert.match(msg,/Jumlah Panggilan Kecemasan: 3/);assert.equal(new URL(buildWhatsAppUrl(msg)).searchParams.get('text'),msg);assert.equal(new URL(buildWhatsAppUrl(msg)).pathname,'/');assert.equal(new URL(buildWhatsAppUrl(msg,'+60 12345')).pathname,'/6012345');r.calls.mecc=4;assert.match(generateWhatsAppMessage(r,'2026-10-03T18:30:00Z'),/Jumlah Panggilan Kecemasan: 5/);});
test('Success only after awaited Firestore save; share handlers have no save/write',()=>{const s=fs.readFileSync('app/page.tsx','utf8');assert.ok(s.indexOf('setFinalSave({report:')>s.indexOf('const saved = await reportRepository.save'));assert.match(s,/if\(saveInFlight.current\) return/);assert.match(s,/setFinalSave\(null\); setShareStatus/);const share=s.slice(s.indexOf('  const openWhatsApp'),s.indexOf('  const printReport'));assert.doesNotMatch(share,/reportRepository|persist\(|firebaseFetch/);assert.match(s,/finalSave && <dialog/);});
test('night totals count saved shifts once, exclude other operational dates and show carry separately',()=>{
 const make=(shift,n,day='2026-10-05',updatedAt='2026-10-05T10:00:00Z')=>({date:day,shift,updatedAt,stats:{l1:n,l2:0,l3:n,l4:n,l5:0,asthmaBay:n},carry:{merah:n,kuning:n+1,observation:n+2},calls:{mecc:0,operator:0,awam:0,palsu:0}});
 const night=make('Malam',3),morning=make('Pagi',1),afternoon=make('Petang',2);
 const msg=generateWhatsAppMessage(night,'2026-10-05T18:00:00Z',[morning,afternoon,make('Pagi',99,'2026-10-04'),make('Pagi',8,'2026-10-05','2026-10-05T09:00:00Z'),night]);
 assert.match(msg,/Jumlah Pesakit Keseluruhan: 24/);assert.match(msg,/Red Zone Keseluruhan: 6/);assert.match(msg,/Green Zone Keseluruhan: 12/);assert.match(msg,/Asthma Bay Keseluruhan: 6/);assert.match(msg,/Carry forward — Red: 1 \| Yellow: 2 \| Observation: 3/);
 assert.doesNotMatch(msg,/belum lengkap/);assert.match(generateWhatsAppMessage(night,'2026-10-05T18:00:00Z',[morning]),/Syif Petang: Belum dihantar/);
 assert.match(generateWhatsAppMessage(night,'2026-10-05T18:00:00Z'),/Jumlah harian tidak tersedia/);
 assert.doesNotMatch(generateWhatsAppMessage(morning,'2026-10-05T18:00:00Z',[morning,afternoon,night]),/JUMLAH KESELURUHAN HARI OPERASI/);
});
